name: New feature or enhancement
description: Suggest or discuss a feature or enhancement for Winlator-Zmod
title: "[Enhancement]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest an improvement for Winlator-Zmod; please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Describe the new feature or enhancement
      description: |
        Please go into as much detail as necessary. 
        If providing examples or suggestions for code changes (Java/C++), please use syntax-highlighted code blocks.
    validations:
      required: true